name: 🔄 Update recent activity

on:
  schedule:
    - cron: '0 * * * *' # Mise à jour toutes les heures
  workflow_dispatch: # Permet de déclencher manuellement l'action

jobs:
  update-readme:
    name: Récupère l'activité publique GitHub
    runs-on: ubuntu-latest
    steps:
      - uses: Readme-Workflows/recent-activity@main
        with:
          GH_USERNAME: mdlnvere
